jdbcUrl = jdbc:mariadb://xipki-db:3306/acme
username = xipki
password = xipkipw

# HikariCP & MySQL/MariaDB recommended tuning flags
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.useServerPrepStmts=true
dataSource.useLocalSessionState=true
dataSource.useLocalTransactionState=true
dataSource.rewriteBatchedStatements=true
dataSource.cacheResultSetMetadata=true
dataSource.cacheServerConfiguration=true
dataSource.elideSetAutoCommits=true
dataSource.maintainTimeStats=false

autoCommit = true
readOnly = false
maximumPoolSize = 10
minimumIdle = 2
connectionTimeout = 10000
idleTimeout = 600000
maxLifetime = 1800000
transactionIsolation = TRANSACTION_READ_COMMITTED
